coc: suggest rewording of reverse-ism clause
WeAllJS/weallbehave pull request #2
Opened 2017-04-11 06:43 UTC by zkat

A while back, a conversation about this CoC came up over at https://github.com/videojs/video.js/pull/4160 when a PR for it was made. I spent some time thinking about it, and I'm wondering if it *is* worth rewording these bits. I'm hoping for some discussion and feedback on whether this is worth changing, whether the new edit is good, or whether the entire premise of changing it is basically preposterous: I don't want to neglect this particular aspect from this CoC, which is _meant_ to be thorough so that everyone knows the ground rules.

2017-04-11 07:36 UTC, AgentAntelope requested changes

2017-04-11 07:36 UTC, AgentAntelope commented on CODE_OF_CONDUCT.md
> +  * Any attempt to deflect unacceptable behavior by using "reverse-isms", or equating "reverse-isms" with oppressive speech about a minority group (which can be an attempt to minimize the legacy and
> attempt to deflect unacceptable behavior

I don't think this is enough to clarify that the act of presenting a ""revers-ism" is itself unacceptable

2017-04-11 07:45 UTC, zkat commented on CODE_OF_CONDUCT.md
> +  * Any attempt to deflect unacceptable behavior by using "reverse-isms", or equating "reverse-isms" with oppressive speech about a minority group (which can be an attempt to minimize the legacy and
Do you have any suggested rewording, or do you feel this entire PR goes counter to what you think is best?

2017-04-11 07:48 UTC, AgentAntelope commented on CODE_OF_CONDUCT.md
> +  * Any attempt to deflect unacceptable behavior by using "reverse-isms", or equating "reverse-isms" with oppressive speech about a minority group (which can be an attempt to minimize the legacy and
I'd say that:
> This project recognizes oppression as directional and will adjust its perspective accordingly.

is a valuable and important sentence; but the problem isn't just people invoking "reverse-isms" as a comparator to existing structural oppression it's also people saying things like "You're racist against white people".

2017-04-11 07:52 UTC, othiym23 commented on CODE_OF_CONDUCT.md
> +  * Any attempt to deflect unacceptable behavior by using "reverse-isms", or equating "reverse-isms" with oppressive speech about a minority group (which can be an attempt to minimize the legacy and
I agree with @AgentAntelope. 

I like the attempt to provide context in the PR, but I also like the directness of the original text. That said, if you're going to clarify things, anyone who "has a tough time" "understanding" what a "reverse -ism" is is probably also going to have difficulty "understanding" what "oppression as directional" means. (Sorry for all the "quotes", but... you know what I mean.)

I think it's worth making a change, but the current proposal isn't as clear as the original. Ganbare!

2017-04-11 13:40 UTC, cjwilburn reviewed
If these questions address issues that you've already discussed, feel free to disregard.

2017-04-11 13:40 UTC, cjwilburn commented on CODE_OF_CONDUCT.md
I'm a tad late to the party, but wondering a bit about the `oppression is directional` part. I understand what it means, and I think I know what you're trying to get across by explicitly stating it, but I'm not sure if this is needed.

2017-04-11 13:40 UTC, cjwilburn commented on CODE_OF_CONDUCT.md
> +  * Any attempt to present "reverse-ism" versions of the above as violations. Examples of reverse-isms are "reverse racism", "reverse sexism", "heterophobia", and "cisphobia". Aggressive/angry langua
Is this around `bigotry` versus `racism`?

2017-07-12 01:48 UTC, marvel3283 approved these changes

2023-07-23 02:44 UTC, closed without merging